name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  brakeman:
    runs-on: ubuntu-latest

    steps:
      - name: Restore build
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: ${{ github.sha }}-build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: brakeman
        run: bundle exec brakeman

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  rubocop:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Restore build
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: ${{ github.sha }}-build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: rubocop
        run: bundle exec rubocop

